# Third-party, unofficial Portage overlay for app-emulation/mocktail.
# Not affiliated with the Mocktail project, the Roblox Corporation or VinegarHQ.
masters = gentoo
thin-manifests = true
manifest-hashes = BLAKE2B SHA512
manifest-required-hashes = BLAKE2B
cache-formats = md5-dict
sign-commits = false
sign-manifests = false
